package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TecharoHQ/anubis/internal/cmd/coreruleset/data"
	"github.com/TecharoHQ/anubis/lib/config"
	"gopkg.in/yaml.v3"
)

var (
	aiCriticalArtifactsFname = flag.String("ai-critical-artifacts-fname", "00-ai-agent-configs.yaml", "filename for ai-critical-artifacts ruleset (crs:930140)")
)

// crs:930140 runs @pmFromFile over REQUEST_FILENAME at phase 1.
//
// @pmFromFile is a case-insensitive Aho-Corasick substring match, so an entry
// matches anywhere in the path and not only at the start. ai-critical-artifacts.data
// depends on that: `.claude/` is meant to catch /docs/.claude/settings.json just
// as much as /.claude/settings.json, and the bare entries `.crush` and
// `.qwen_code` are meant to catch any file whose name contains them.
//
// REQUEST_FILENAME is the path without the query string, which is what Anubis
// exposes as `path`, so this rule ports cleanly. Two upstream transforms have no
// equivalent here: t:urlDecodeUni (Go decodes the path exactly once, so
// %252e-style double encoding survives) and t:normalizePathWin (backslashes are
// not folded to forward slashes).
func aiCriticalArtifacts() error {
	fout, err := os.Create(filepath.Join(*outDir, *aiCriticalArtifactsFname))
	if err != nil {
		return err
	}

	defer func() {
		_ = fout.Close()
	}()

	fmt.Fprintf(fout, "# generated by %s\n# edit internal/cmd/coreruleset to change this\n", filepath.Base(os.Args[0]))

	data, err := data.Files.ReadFile("ai-critical-artifacts.txt")
	if err != nil {
		return err
	}

	var needles []string

	for line := range strings.SplitSeq(string(data), "\n") {
		if strings.HasPrefix(line, "#") || line == "" {
			continue // ignore comments and empty lines
		}

		// Take each entry verbatim as a substring needle. Do not root it with
		// a leading slash and do not force a trailing slash: either one would
		// narrow the match below what upstream does.
		needles = append(needles, fmt.Sprintf("%q", strings.ToLower(line)))
	}

	// lowerAscii on both sides reproduces the case folding that @pm does. One
	// expression over a list literal keeps the AST small, which the CEL checker
	// handles far faster than a chain of one term per entry.
	expr := fmt.Sprintf("[%s].exists(p, path.lowerAscii().contains(p))", strings.Join(needles, ", "))

	result := []*config.BotConfig{
		{
			Name:   "coreruleset-930140-ai-critical-artifacts",
			Action: config.RuleWeigh,
			// crs:930140 has severity CRITICAL, which maps to
			// setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'
			// where tx.critical_anomaly_score is 5.
			Weight:     &config.Weight{Adjust: criticalAnomalyScore},
			Expression: &config.ExpressionOrList{Expression: expr},
		},
	}

	enc := yaml.NewEncoder(fout)
	return enc.Encode(result)
}
