package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TecharoHQ/anubis/internal/cmd/coreruleset/data"
	"github.com/TecharoHQ/anubis/lib/config"
	"gopkg.in/yaml.v3"
)

var (
	lfiOsFilesFname = flag.String("lfi-os-files-fname", "00-lfi-os-files.yaml", "filename for lfi-os-files ruleset (crs:930120)")
)

// criticalAnomalyScore is the value CRS gives tx.critical_anomaly_score, which
// severity:'CRITICAL' rules add to tx.inbound_anomaly_score_pl1.
const criticalAnomalyScore = 5

// crs:930120 runs @pmFromFile over
// REQUEST_COOKIES|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/*|XML://@*
// at phase 2. @pmFromFile is a case-insensitive substring match, hence the
// lowerAscii calls below and the lowercased needle.
//
// Each target upstream shares one rule. Here each target gets its own rule so
// that operators can weigh or drop them one at a time.
//
// Not ported:
//
//   - XML:/* and XML://@* have no Anubis equivalent, there is no request body
//     variable in lib/policy/expressions.
//   - ARGS covers the query string only. Anubis does not parse POST bodies, so
//     form fields are invisible to these rules.
//   - REQUEST_COOKIES and REQUEST_COOKIES_NAMES collapse into one rule. Anubis
//     exposes the raw Cookie header and not a parsed cookie map, so a match
//     cannot tell a cookie name from a cookie value.
func lfiOsFiles() error {
	fout, err := os.Create(filepath.Join(*outDir, *lfiOsFilesFname))
	if err != nil {
		return err
	}

	defer func() {
		_ = fout.Close()
	}()

	fmt.Fprintf(fout, "# generated by %s\n# edit internal/cmd/coreruleset to change this\n", filepath.Base(os.Args[0]))

	newRule := func(name string, expr *config.ExpressionOrList) *config.BotConfig {
		return &config.BotConfig{
			Name:       name,
			Action:     config.RuleWeigh,
			Weight:     &config.Weight{Adjust: criticalAnomalyScore},
			Expression: expr,
		}
	}

	data, err := data.Files.ReadFile("lfi-os-files.txt")
	if err != nil {
		return err
	}

	var (
		needles    []string // lowercased, matched as substrings
		pathExact  []string // rooted, matched with ==
		pathPrefix []string // rooted, matched with startsWith
	)

	for line := range strings.SplitSeq(string(data), "\n") {
		if strings.HasPrefix(line, "#") || line == "" {
			continue // ignore comments and empty lines
		}

		// @pmFromFile takes each entry verbatim as a substring needle and
		// folds case. Do not root or slash-terminate these.
		needles = append(needles, strings.ToLower(line))

		// The path rule keeps its original rooted, exact-or-prefix shape.
		path := line
		if !strings.HasPrefix(path, "/") {
			path = "/" + path
		}

		switch {
		case strings.HasSuffix(path, "/"):
			pathPrefix = append(pathPrefix, path)
		default:
			pathExact = append(pathExact, path)
		}
	}

	// Anubis joins an Any list into one `(a) || (b) || ...` program, so a
	// 1081-entry list repeats the whole needle test 1081 times in the AST.
	// Emitting one expression over a CEL list literal keeps the same result
	// with a far smaller AST, which the CEL checker handles much faster.
	celList := func(items []string) string {
		quoted := make([]string, 0, len(items))
		for _, s := range items {
			quoted = append(quoted, fmt.Sprintf("%q", s))
		}
		return "[" + strings.Join(quoted, ", ") + "]"
	}

	patterns := celList(needles)

	// `path in [...]` is one list membership test, so it allocates once
	// instead of once per entry. It only works for exact matches, which is
	// why the prefixes stay an || chain. That chain is short, 106 entries,
	// and an exists() macro over it measured slower than the chain.
	var pathExpr strings.Builder
	fmt.Fprintf(&pathExpr, "path in %s", celList(pathExact))
	for _, p := range pathPrefix {
		fmt.Fprintf(&pathExpr, " || path.startsWith(%q)", p)
	}

	result := []*config.BotConfig{
		// ARGS: the value of every query parameter.
		newRule("coreruleset-930120-lfi-os-files-args", &config.ExpressionOrList{
			Expression: fmt.Sprintf("query.exists(k, %s.exists(p, query[k].lowerAscii().contains(p)))", patterns),
		}),

		// ARGS_NAMES: the name of every query parameter.
		newRule("coreruleset-930120-lfi-os-files-args-names", &config.ExpressionOrList{
			Expression: fmt.Sprintf("query.exists(k, %s.exists(p, k.lowerAscii().contains(p)))", patterns),
		}),

		// REQUEST_COOKIES and REQUEST_COOKIES_NAMES, as one raw header match.
		// headers[k] raises on a missing key, so the guard has to run first.
		// Hoisting it out of the list keeps that index operation to one.
		newRule("coreruleset-930120-lfi-os-files-cookies", &config.ExpressionOrList{
			Expression: fmt.Sprintf(`"Cookie" in headers && %s.exists(p, headers["Cookie"].lowerAscii().contains(p))`, patterns),
		}),

		// Not an upstream 930120 target. crs:930120 never looks at the path.
		// This rule keeps the blocklist working against direct requests such
		// as GET /etc/passwd, which upstream leaves to other rules.
		newRule("lfi-os-files-path", &config.ExpressionOrList{Expression: pathExpr.String()}),
	}

	enc := yaml.NewEncoder(fout)
	return enc.Encode(result)
}
