package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TecharoHQ/anubis/internal/cmd/coreruleset/data"
	"github.com/TecharoHQ/anubis/lib/config"
	"gopkg.in/yaml.v3"
)

var (
	restrictedFilesFname = flag.String("restricted-files-fname", "00-restricted-files.yaml", "filename for restricted-files ruleset (crs:930130)")
)

func restrictedFiles() error {
	fout, err := os.Create(filepath.Join(*outDir, *restrictedFilesFname))
	if err != nil {
		return err
	}

	defer func() {
		_ = fout.Close()
	}()

	fmt.Fprintf(fout, "# generated by %s\n# edit internal/cmd/coreruleset to change this\n", filepath.Base(os.Args[0]))

	result := []*config.BotConfig{
		{
			Name:   "coreruleset-930130-restricted-files",
			Action: config.RuleWeigh,
			// crs:930130 has severity CRITICAL, which maps to
			// setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'
			// where tx.critical_anomaly_score is 5.
			Weight: &config.Weight{Adjust: 5},
			Expression: &config.ExpressionOrList{
				Any: []string{},
			},
		},
	}

	data, err := data.Files.ReadFile("restricted-files.txt")
	if err != nil {
		return err
	}

	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "#") || line == "" {
			continue // ignore comments and empty lines
		}

		// some entries in restricted-files.data are already rooted, don't
		// double up the leading slash or the rule can never match.
		if !strings.HasPrefix(line, "/") {
			line = "/" + line
		}

		switch {
		case strings.HasSuffix(line, "/"):
			result[0].Expression.Any = append(result[0].Expression.Any, fmt.Sprintf("path.startsWith(%q)", line))
		default:
			result[0].Expression.Any = append(result[0].Expression.Any, fmt.Sprintf("path == %q", line))
		}
	}

	enc := yaml.NewEncoder(fout)
	return enc.Encode(result)
}
