name: Bug report
description: Create a report to help us improve

body:
  - type: textarea
    id: description-of-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I can reliably get an error when...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior.
      placeholder: |
        1. Go to the following url...
        2. Click on...
        3. You get the following error: ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
        Ideally also describe *why* you expect it to happen.
      placeholder: Instead of displaying an error, it would...
    validations:
      required: true

  - type: input
    id: version-os
    attributes:
      label: Your operating system and its version.
      description: Unsure? Visit https://whatsmyos.com/
      placeholder: Android 13
    validations:
      required: true

  - type: input
    id: version-browser
    attributes:
      label: Your browser and its version.
      description: Unsure? Visit https://www.whatsmybrowser.org/
      placeholder: Firefox 142
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

