#!/usr/bin/env bash
#
# CW(Xe): Script was generated by Claude after I tried to do this manually and
# gave up.
#
# Build binaryen tools (wasm2js, wasm-opt) as WASI preview 1 WebAssembly
# modules. See the TOOLS array below to add or remove targets.
#
# Output: ./<tool>_<BINARYEN_VERSION>.wasm
#         (default wasm2js_130.wasm, wasm-opt_130.wasm)
#
# Dependencies are fetched automatically if missing: wasi-sdk is downloaded
# from its GitHub release and binaryen is git-cloned at the requested tag.
# Pin versions with the WASI_SDK_VERSION and BINARYEN_VERSION env vars.
#
# How it works / notable decisions:
#
#   * Toolchain: we use the wasi-sdk CMake toolchain file `wasi-sdk-p1.cmake`,
#     which targets `wasm32-wasip1` and points CMake at the bundled clang/lld.
#
#   * Static binary: WASI has no dynamic linker, so libbinaryen is built as a
#     static archive (-DBUILD_SHARED_LIBS=OFF) and statically linked into the
#     final module. This is the only thing that links on WASI.
#
#   * C++ exceptions: binaryen's parser and tools use `throw`, so we cannot
#     build with -fno-exceptions. wasi-sdk ships two libc++ flavors: the default
#     `noeh` (no exceptions) and an `eh` variant. Passing `-fwasm-exceptions`
#     makes the clang driver select the `eh` include/lib dirs. We also link
#     `-lunwind` to satisfy the `_Unwind_*` / exception-tag symbols.
#
#   * EH encoding: by default LLVM emits the *legacy* wasm exception-handling
#     opcodes (`try`/`catch`), which modern runtimes (e.g. wasmtime >= ~45) no
#     longer accept. `-mllvm -wasm-use-legacy-eh=false` makes it emit the
#     standardized exnref-based EH (`try_table`) instead, so the module runs on
#     current runtimes with the exceptions proposal enabled.
#
#   * Threads: binaryen calls find_package(Threads) and links pthread (wasi-libc
#     provides stubs). At runtime ThreadPool::getNumCores() returns 1 on wasip1,
#     so no threads are ever spawned and it runs single-threaded.
#
#   * Reproducibility: the goal is a byte-for-byte identical module on any
#     machine. Ninja invokes clang with absolute source paths, so __FILE__
#     (used all over binaryen via WASM_UNREACHABLE) would otherwise bake the
#     build machine's checkout path into the module's data segments. We rewrite
#     that prefix to a stable token with -ffile-prefix-map so the output does
#     not depend on where the tree lives. Everything else feeding the module is
#     already pinned (wasi-sdk version, binaryen tag, compile/link flags), and
#     the wasm format carries no build timestamp, so the raw clang/lld output is
#     deterministic. We deliberately do NOT post-process with wasm-opt: its
#     availability and version vary per machine, which would defeat the
#     guarantee. The module ships exactly as the linker emits it.
#
#   * ASLR: the wasi-sdk clang that compiles binaryen has address-sensitive
#     ordering in its WebAssembly exception-handling codegen -- pointer values
#     leak into the iteration order of a few passes, which shuffles a handful of
#     try_table basic blocks and their branch labels. With address-space layout
#     randomization on, the same source compiles to ~29 differing bytes from one
#     run to the next. We pin pointer layout by re-exec'ing the whole build under
#     `setarch -R` (ADDR_NO_RANDOMIZE), which is inherited by cmake/ninja/clang.
#     This is Linux-only; see the re-exec guard below.
#
# To run the resulting module, the host runtime must enable the exceptions
# proposal and grant filesystem access, e.g.:
#
#   wasmtime run -W exceptions=y --dir . ./wasm2js_130.wasm input.wasm -o out.js
#
set -euo pipefail

# Reproducibility: disable address-space randomization for the whole build so
# the wasi-sdk clang's pointer-sensitive codegen is deterministic (see the ASLR
# note in the header comment). The ADDR_NO_RANDOMIZE personality is inherited by
# every child process (cmake, ninja, clang, lld), so re-exec'ing the script once
# under setarch covers the entire toolchain. setarch is Linux/util-linux only;
# elsewhere we proceed without it and the output may not be bit-identical.
if [[ "$(uname -s)" == "Linux" && -z "${WASM2JS_NO_ASLR:-}" ]]; then
	if command -v setarch >/dev/null 2>&1; then
		export WASM2JS_NO_ASLR=1
		exec setarch "$(uname -m)" -R "$0" "$@"
	fi
	echo ">> warning: setarch not found; build may not be byte-for-byte reproducible" >&2
fi

# Pin any timestamp a tool in the chain might embed. Nothing in the current
# toolchain consumes this (the wasm format has no build-time field and we emit
# no debug info), but exporting it keeps the build deterministic if a future
# wasi-sdk or binaryen starts honoring it. Fixed constant, not "now".
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1700000000}"

# Resolve the directory this script lives in so it works from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# --- Versions (override via the environment) -------------------------------
# wasi-sdk: full release version, e.g. 33.0. The GitHub release tag uses only
# the major component (wasi-sdk-33) while the tarball uses the full version.
WASI_SDK_VERSION="${WASI_SDK_VERSION:-33.0}"
# binaryen: the numeric release, used both for the git tag (version_130) and
# the output filename (wasm2js_130.wasm).
BINARYEN_VERSION="${BINARYEN_VERSION:-130}"

# Map the host's uname onto wasi-sdk's <arch>-<os> asset naming.
case "$(uname -s)" in
Darwin) WASI_SDK_OS="macos" ;;
Linux) WASI_SDK_OS="linux" ;;
*)
	echo "error: unsupported OS $(uname -s); set WASI_SDK to a prebuilt sdk" >&2
	exit 1
	;;
esac
case "$(uname -m)" in
x86_64 | amd64) WASI_SDK_ARCH="x86_64" ;;
arm64 | aarch64) WASI_SDK_ARCH="arm64" ;;
*)
	echo "error: unsupported arch $(uname -m); set WASI_SDK to a prebuilt sdk" >&2
	exit 1
	;;
esac

WASI_SDK_MAJOR="${WASI_SDK_VERSION%%.*}"
WASI_SDK_DIRNAME="wasi-sdk-${WASI_SDK_VERSION}-${WASI_SDK_ARCH}-${WASI_SDK_OS}"
WASI_SDK_URL="https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK_MAJOR}/${WASI_SDK_DIRNAME}.tar.gz"
BINARYEN_TAG="version_${BINARYEN_VERSION}"
BINARYEN_URL="https://github.com/WebAssembly/binaryen.git"

# All build inputs live under ./var; outputs land in the script directory.
VAR_DIR="$SCRIPT_DIR/var"

WASI_SDK="${WASI_SDK:-$VAR_DIR/$WASI_SDK_DIRNAME}"
BINARYEN_SRC="$VAR_DIR/binaryen"
BUILD_DIR="$BINARYEN_SRC/build-wasi"

TOOLCHAIN="$WASI_SDK/share/cmake/wasi-sdk-p1.cmake"

mkdir -p "$VAR_DIR"

# --- Fetch wasi-sdk ---------------------------------------------------------
if [[ ! -f "$TOOLCHAIN" ]]; then
	echo ">> Downloading wasi-sdk $WASI_SDK_VERSION"
	echo "   $WASI_SDK_URL"
	tmp_tarball="$(mktemp "$VAR_DIR/.wasi-sdk.XXXXXX.tar.gz")"
	trap 'rm -f "$tmp_tarball"' EXIT
	curl -fL --retry 3 -o "$tmp_tarball" "$WASI_SDK_URL"
	# The tarball unpacks to $WASI_SDK_DIRNAME/ in the destination directory.
	tar -xzf "$tmp_tarball" -C "$VAR_DIR"
	rm -f "$tmp_tarball"
	trap - EXIT
fi

if [[ ! -f "$TOOLCHAIN" ]]; then
	echo "error: wasi-sdk toolchain not found at $TOOLCHAIN" >&2
	echo "       set WASI_SDK to the wasi-sdk install prefix" >&2
	exit 1
fi

# --- Fetch binaryen ---------------------------------------------------------
if [[ ! -d "$BINARYEN_SRC/.git" ]]; then
	echo ">> Cloning binaryen at $BINARYEN_TAG"
	git clone --depth 1 --branch "$BINARYEN_TAG" --recurse-submodules \
		"$BINARYEN_URL" "$BINARYEN_SRC"
fi

# Flags that enable standardized wasm exception handling against wasi-sdk's
# `eh` libc++ variant. Needed at both compile and link time.
EH_COMPILE_FLAGS="-fwasm-exceptions -mllvm -wasm-use-legacy-eh=false"
EH_LINK_FLAGS="-fwasm-exceptions -lunwind"

# Reproducibility: strip the absolute checkout path out of every __FILE__ so the
# module is identical regardless of where binaryen was cloned. BUILD_DIR lives
# under BINARYEN_SRC, so generated-source paths are normalized by the same map.
REPRO_COMPILE_FLAGS="-ffile-prefix-map=$BINARYEN_SRC=."

echo ">> Configuring (wasm32-wasip1, static, exceptions=exnref)"
cmake -S "$BINARYEN_SRC" -B "$BUILD_DIR" -G Ninja \
	-DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN" \
	-DWASI_SDK_PREFIX="$WASI_SDK" \
	-DCMAKE_BUILD_TYPE=Release \
	-DBUILD_TESTS=OFF \
	-DBUILD_SHARED_LIBS=OFF \
	-DENABLE_WERROR=OFF \
	-DINSTALL_LIBS=OFF \
	-DCMAKE_C_FLAGS="$EH_COMPILE_FLAGS $REPRO_COMPILE_FLAGS" \
	-DCMAKE_CXX_FLAGS="$EH_COMPILE_FLAGS $REPRO_COMPILE_FLAGS" \
	-DCMAKE_EXE_LINKER_FLAGS="$EH_LINK_FLAGS"

# Tools to build, as binaryen CMake target names. Each is emitted to
# ./<tool>_<BINARYEN_VERSION>.wasm.
TOOLS=(wasm2js wasm-opt)

echo ">> Building: ${TOOLS[*]}"
cmake --build "$BUILD_DIR" --target "${TOOLS[@]}"

# Install the linker output verbatim. We intentionally skip any wasm-opt pass:
# optimizing here would make the result depend on whichever wasm-opt happens to
# be installed, which is exactly the non-determinism we are eliminating. The
# raw module is already reproducible thanks to the pinned toolchain and the
# -ffile-prefix-map applied above.
BUILD_BIN="$BUILD_DIR/bin"

for tool in "${TOOLS[@]}"; do
	out="./${tool}_${BINARYEN_VERSION}.wasm"
	echo ">> Installing $tool -> $out"
	cp "$BUILD_BIN/$tool" "$out"
	ls -l "$out" | awk '{print "   size:", $5, "bytes"}'
done

echo ">> Done. Outputs in $SCRIPT_DIR:"
ls -1 ./*_"${BINARYEN_VERSION}".wasm
