apiVersion: v1
kind: ServiceAccount
metadata:
  name: anubis-k3k
  namespace: ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anubis-k3k
  namespace: ci
rules:
  - apiGroups: ["k3k.io"]
    resources: ["clusters"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anubis-k3k
  namespace: ci
subjects:
  - kind: ServiceAccount
    name: anubis-k3k
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anubis-k3k
