name: Docker image builds (pull requests)

on:
  pull_request:
    branches: ["main"]

env:
  DOCKER_METADATA_SET_OUTPUT_ENV: "true"

permissions:
  contents: read

jobs:
  ko_pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-tags: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Binaryen
        uses: Zxilly/setup-binaryen@3cda60f50c9575dff0dc7a1d27cdf1306333a7c5 # v1.1.0
        with:
          version: "130"

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.11.0"
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "stable"
      - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1.15.1
        with:
          cache: false
          target: wasm32-unknown-unknown

      - name: CLI deps
        run: |
          sudo apt-get update
          sudo apt-get -y install brotli zstd

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push
        id: build
        run: |
          npm ci
          npm run container
        env:
          PULL_REQUEST_ID: ${{ github.event.number }}
          DOCKER_REPO: ghcr.io/${{ github.repository }}
          SLOG_LEVEL: debug

      - run: |
          echo "Test this with:"
          echo "docker pull ${DOCKER_IMAGE}"
        env:
          DOCKER_IMAGE: ${{ steps.build.outputs.docker_image }}
