name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: write

jobs:
  go_tests:
    #runs-on: alrest-techarohq
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: build essential and haproxy
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential haproxy

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.11.0"
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "stable"

      - name: Cache playwright binaries
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/go.sum') }}

      - name: install node deps
        run: |
          npm ci

      - name: install playwright browsers
        run: |
          npx --no-install playwright@1.52.0 install --with-deps
          npx --no-install playwright@1.52.0 run-server --port 9001 &

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint with staticcheck
        uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
        with:
          version: "latest"

      - name: Govulncheck
        run: |
          go tool govulncheck ./... ||:
