name: Package builds (stable)

on:
  workflow_dispatch:
  # release:
  #   types: [published]

permissions:
  contents: write
  actions: write

jobs:
  package_builds:
    #runs-on: alrest-techarohq
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-tags: true
          fetch-depth: 0

      - name: build essential
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Setup Homebrew cellar cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            /home/linuxbrew/.linuxbrew/Cellar
            /home/linuxbrew/.linuxbrew/bin
            /home/linuxbrew/.linuxbrew/etc
            /home/linuxbrew/.linuxbrew/include
            /home/linuxbrew/.linuxbrew/lib
            /home/linuxbrew/.linuxbrew/opt
            /home/linuxbrew/.linuxbrew/sbin
            /home/linuxbrew/.linuxbrew/share
            /home/linuxbrew/.linuxbrew/var
          key: ${{ runner.os }}-go-homebrew-cellar-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-homebrew-cellar-

      - name: Install Brew dependencies
        run: |
          brew bundle

      - name: Setup Golang caches
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1.15.1
        with:
          cache: false
          target: wasm32-unknown-unknown

      - name: Setup Binaryen
        uses: Aandreba/setup-binaryen@77f25f9d7d30f09667a2535888bf9516b31a4cd7 # v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 108

      - name: install node deps
        run: |
          npm ci

      - name: Build Packages
        run: |
          go tool yeet

      - name: Upload released artifacts
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          RELEASE_VERSION: ${{github.event.release.tag_name}}
        shell: bash
        run: |
          RELEASE="${RELEASE_VERSION}"
          cd var
          for file in *; do
            gh release upload $RELEASE $file
          done
