name: Docker

on:
  push:
    paths:
      - "test/ssh-ci/Dockerfile"
      - "test/ssh-ci/docker-bake.hcl"
      - ".github/workflows/ssh-ci-image-test.yml"

jobs:
  ssh-ci-image-test:
    name: "Ensure SSH CI image builds cleanly when changed"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-tags: true
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build image
        run: |
          cd ./test/ssh-ci
          docker buildx bake --pull
